@base_url = http://localhost
@port = 3500
@url = {{base_url}}:{{port}}
@product_api = {{url}}/products
@account_api = {{url}}/account

GET {{product_api}} HTTP/1.1
###

GET {{product_api}}/total HTTP/1.1
###

GET {{product_api}}/price?min=1000&max=2000 HTTP/1.1
###

GET {{product_api}}/3 HTTP/1.1
###

GET {{product_api}}/search?search=date HTTP/1.1
###


POST {{product_api}} HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

jame post
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stock"

100 
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

690
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="demo.png"
Content-Type: image/png

< ./demo01.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###
PUT {{product_api}}/7 HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="name"

jame updated
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="stock"

100 
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="price"

690
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="image"; filename="demo.png"
Content-Type: image/png

< ./demo01.png
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###

DELETE {{product_api}}/3 HTTP/1.1
###

POST {{account_api}}/register HTTP/1.1
Content-Type:application/json 

{
    "username": "jame03",
    "password": "password la",
    "role" : "User"
} 
###

# @name login
POST {{account_api}}/login HTTP/1.1
Content-Type: application/json

{
    "username": "jame03",
    "password": "password la"
}
###

GET {{account_api}}/info HTTP/1.1
###

GET {{url}}/user HTTP/1.1
###

GET {{url}}/user/search?search=12 HTTP/1.1
###

GET {{url}}/user/7 HTTP/1.1
###

POST {{url}}/user HTTP/1.1
Content-Type: application/json

{
    "username":"blacktyr5t",
    "password" : "piyawat5",
    "information" : {
        "email" : "jame@hotmail",
        "address": "bangna",
       "gender" : "MALE",
       "birth" : "2023-10-23T10:42:10.190Z" 
    }
}
###

PUT {{url}}/user/7 HTTP/1.1
Content-Type: application/json

{
    "username":"Hibroooo777",
    "password" : "piyawat7",
    "information" : {
        "email" : "jame@hotmail",
        "address": "bangpoooo",
       "gender" : "MALE",
       "birth" : "2023-10-23T10:42:10.190Z" 
    }
}
###

DELETE {{url}}/user/5 HTTP/1.1